apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: culture-threads-api
  namespace: argocd
  labels:
    app: culture-threads-api
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/developedbydmac/culture-threads-gcp.git
    targetRevision: HEAD
    path: k8s/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: culture-threads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: culture-threads-infrastructure
  namespace: argocd
  labels:
    app: culture-threads-infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/developedbydmac/culture-threads-gcp.git
    targetRevision: HEAD
    path: k8s
    directory:
      include: "{configmap,namespace,service}.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: culture-threads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
